# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DogBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageDog', models.ImageField(upload_to='')),
                ('imageDate', models.DateField()),
                ('imageTag', models.ManyToManyField(to='DogBase.Dog')),
            ],
        ),
    ]
