# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoBase', '0002_auto_20170822_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogimage',
            name='imageForFace',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
