# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DogBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePairName', models.CharField(max_length=200)),
                ('imagePair', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairDate', models.DateField()),
                ('pairLiter', models.CharField(max_length=50)),
                ('pairImage', models.ImageField(upload_to='')),
                ('pairWanted', models.BooleanField()),
                ('pairIsPast', models.BooleanField()),
                ('pairRes', models.TextField()),
                ('pairF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='DogBase.Dog')),
                ('pairM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='DogBase.Dog')),
            ],
        ),
        migrations.AddField(
            model_name='imagespair',
            name='imagePairTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewPuppies.Pair'),
        ),
    ]
