# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewPuppies', '0002_auto_20170822_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='pairImage',
            field=models.ImageField(upload_to='DogPairImages'),
        ),
    ]
