# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timefield',
            field=models.DateTimeField(),
        ),
    ]
